main = ".open-next/worker.js"
name = "wesbos"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# The binding name must be "ASSETS" when the cache is enabled
assets = { directory = ".open-next/assets", binding = "ASSETS" }
# Browser for Puppeteer
browser = { binding = "MYBROWSER" }

[[ d1_databases ]]
binding = "DB"
database_name = "wes-bos-social-cache"
database_id = "7a07786d-8f53-4578-86a4-933d939c16bb"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "OG"
id = "d5ca915ca3b54dc48a19b70deaf274af"

[[kv_namespaces]]
binding = "NEXT_CACHE_WORKERS_KV"
id = "e09de51f462241728f22e36bb3bcbedc"
